# The Module Name is used as prefix for all contained resources.
Module: My.Wiki

# The Module Version is shown in the CloudFormation stack and Lambda function descriptions.
Version: 1.0-DEV

# The Module Description is shown in the AWS CloudFormation console with the version number.
Description: Module description

# The Items section defines values and resources for the module.
Items:

  - Resource: Table
    Scope:
      - Wiki
    Description: WikiStore
    Type: AWS::DynamoDB::Table
    Allow: Full
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: WikiId
          AttributeType: S
      KeySchema:
        - AttributeName: WikiId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  - Function: Wiki
    Description: Beat The Wiki Game
    Memory: 256
    Timeout: 30
    Sources:
      - DynamoDB: Table
        BatchSize: 15
